// registry/index.ts

export const Index = [
  {
    name: 'neubrutal-button',
    type: 'ui',
    files: ['ui/buttons/neubrutal-button.tsx'],
    category: 'buttons',
    description: 'A high-end button with modern hover effects and bold styling.',
    install: 'npm install framer-motion',
    dependencies: ['framer-motion'],
    interactionType: [{ type: 'Hover', description: 'Interactive hover scaling' }],
    howToUse: `import { NeubrutalButton } from "@/components/ui/buttons/neubrutal-button";`,
    keepInMind: 'Ensure Framer Motion is installed.',
    contact: 'raj.shytanimo@gmail.com',
    license: 'MIT',
  },
  {
    name: 'dot-cursor',
    type: 'ui',
    files: ['ui/cursors/dot-cursor.tsx'],
    category: 'cursors',
    description: 'A smooth, reactive custom cursor for modern web interfaces.',
    install: 'npm install framer-motion',
    dependencies: ['framer-motion'],
    interactionType: [{ type: 'Mouse Move', description: 'Follows cursor movement' }],
    howToUse: `import { DotCursor } from "@/components/ui/cursors/dot-cursor";`,
    keepInMind: 'Set cursor to none on body.',
    contact: 'raj.shytanimo@gmail.com',
    license: 'MIT',
  },
  {
    name: 'floating-navbar',
    type: 'ui',
    files: ['ui/navbars/floating-navbar.tsx'],
    category: 'navbars',
    description: 'A sophisticated navigation bar with GSAP animations and audio toggles.',
    install: 'npm install gsap',
    dependencies: ['gsap'],
    interactionType: [{ type: 'Scroll', description: 'Hides/shows on scroll' }],
    howToUse: `import { FloatingNavbar } from "@/components/ui/navbars/floating-navbar";`,
    keepInMind: 'Requires GSAP integration.',
    contact: 'raj.shytanimo@gmail.com',
    license: 'MIT',
  },
  {
    name: 'minimal-scrollbar',
    type: 'ui',
    files: ['ui/scrollbars/minimal-scrollbar.tsx'],
    category: 'scrollbars',
    description: 'Custom, minimalist scrollbar with smooth transition properties.',
    install: '',
    dependencies: [],
    interactionType: [{ type: 'Scroll', description: 'Native scroll behavior' }],
    howToUse: `import { MinimalScrollbar } from "@/components/ui/scrollbars/minimal-scrollbar";`,
    keepInMind: 'CSS-only implementation.',
    contact: 'raj.shytanimo@gmail.com',
    license: 'MIT',
  },
  {
    name: 'strike-reveal',
    type: 'ui',
    files: ['ui/hover-effects/strike-reveal.tsx'],
    category: 'hover-effects',
    description: 'Text reveal effect with a striking diagonal animation.',
    install: '',
    dependencies: ['framer-motion'],
    interactionType: [{ type: 'Hover', description: 'Staggered reveal animation' }],
    howToUse: `import { StrikeReveal } from "@/components/ui/hover-effects/strike-reveal";`,
    keepInMind: 'Best for headers.',
    contact: 'raj.shytanimo@gmail.com',
    license: 'MIT',
  },
  {
    name: 'infinity-slider',
    type: 'ui',
    files: ['ui/3d-sliders/infinity-slider.tsx'],
    category: '3d-sliders',
    description: 'A 3D infinite slider loop using physics-based motion.',
    install: '',
    dependencies: ['framer-motion'],
    interactionType: [{ type: 'Drag', description: 'Infinite 3D rotation' }],
    howToUse: `import { InfinitySlider } from "@/components/ui/3d-sliders/infinity-slider";`,
    keepInMind: 'Use hardware-accelerated containers.',
    contact: 'raj.shytanimo@gmail.com',
    license: 'MIT',
  },
  {
    name: 'stroke-cards',
    type: 'ui',
    files: ['ui/cards/stroke-cards.tsx'],
    category: 'cards',
    description: 'Card component with an animated stroke effect on border.',
    install: '',
    dependencies: [],
    interactionType: [{ type: 'Hover', description: 'Border stroke activation' }],
    howToUse: `import { StrokeCards } from "@/components/ui/cards/stroke-cards";`,
    keepInMind: 'Optimized for grid layouts.',
    contact: 'raj.shytanimo@gmail.com',
    license: 'MIT',
  },
  {
    name: 'arc-slider',
    type: 'ui',
    files: ['ui/3d-sliders/arc-slider.tsx'],
    category: '3d-sliders',
    description: '3D slider that follows an arc path for dynamic visuals.',
    install: '',
    dependencies: ['framer-motion'],
    interactionType: [{ type: 'Drag', description: 'Arc-based drag' }],
    howToUse: `import { ArcSlider } from "@/components/ui/3d-sliders/arc-slider";`,
    keepInMind: 'Responsive container required.',
    contact: 'raj.shytanimo@gmail.com',
    license: 'MIT',
  },
  {
    name: 'animated-header',
    type: 'ui',
    files: ['ui/scroll-effects/animated-header.tsx'],
    category: 'scroll-effects',
    description: 'Complex header that reacts to scroll velocity and position.',
    install: 'npm install gsap @studio-freight/lenis',
    dependencies: ['gsap', '@studio-freight/lenis'],
    interactionType: [{ type: 'Scroll', description: 'Velocity-based header shrink' }],
    howToUse: `import { AnimatedHeader } from "@/components/ui/scroll-effects/animated-header";`,
    keepInMind: 'Requires Lenis smooth scrolling.',
    contact: 'raj.shytanimo@gmail.com',
    license: 'MIT',
  },
];