import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import path from 'path';
import { registry } from '../registry/index';

const OUTPUT_DIR = path.join(process.cwd(), '__registry__');
const OUTPUT_PATH = path.join(OUTPUT_DIR, 'index.ts');

async function buildRegistry() {
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR);
  }

  let indexContent = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
`;

  registry.forEach((item: any) => {
    const filePath = path.join(process.cwd(), 'registry', item.files[0]);
    const rawContent = existsSync(filePath)
      ? readFileSync(filePath, 'utf8')
      : '';

    // FIX: Escape backticks and dollar signs to prevent breaking template literals
    const importPath = item.files[0].replace(/\.tsx?$/, "");

// FIX: Escape backticks and dollar signs to prevent breaking the template literal
const safeContent = rawContent.replace(/`/g, "\\`").replace(/\$/g, "\\$");
const safeDescription = (item.description || "").replace(/`/g, "\\`").replace(/\$/g, "\\$");

indexContent += `    "${item.name}": {
      name: "${item.name}",
      type: "${item.type}",
      // FIX: Ensure the import points to the correct relative path
      component: React.lazy(() => import("../registry/${importPath}")),
      files: ${JSON.stringify(item.files)},
      category: "${item.category || 'undefined'}",
      content: \`${safeContent}\`,
      description: \`${safeDescription}\`,
      install: "${item.install || ''}",
    },
`;
  });

  indexContent += `  }
};`;

  writeFileSync(OUTPUT_PATH, indexContent);
  console.log('✅ Slash UI Registry generated!');
}

buildRegistry();
