// @ts-nocheck
import { writeFileSync, existsSync, mkdirSync, readFileSync } from 'fs';
import path from 'path';
import { Index } from '../registry/index';

const OUTPUT_DIR = path.join(process.cwd(), '__registry__');
const OUTPUT_PATH = path.join(OUTPUT_DIR, 'index.ts');
const COMPONENTS_PATH = path.join(OUTPUT_DIR, 'components.ts');

async function buildRegistry() {
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR);
  }

  const escape = (str: string) =>
    (str || '').replace(/`/g, '\\`').replace(/\$/g, '\\$');

  let indexContent = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
`;

  Index.forEach((item: any) => {
    const componentPath = item.files[0].replace(/\.tsx?$/, '');
    const sourceFilePath = path.join(process.cwd(), 'registry', item.files[0]);
    const rawContent = existsSync(sourceFilePath)
      ? readFileSync(sourceFilePath, 'utf8')
      : '';

    indexContent += `    "${item.name}": {
      name: "${item.name}",
      type: "${item.type}",
      component: React.lazy(() => import("@/registry/${componentPath}")),
      files: ${JSON.stringify(item.files)},
      category: "${item.category || 'undefined'}",
      content: \`${escape(rawContent)}\`,
      description: \`${escape(item.description)}\`,
      install: "${item.install || ''}",
      dependencies: ${JSON.stringify(item.dependencies || [])},
      interactionType: ${JSON.stringify(item.interactionType || [])},
      howToUse: \`${escape(item.howToUse)}\`,
    },
`;
  });

  indexContent += `  }
};`;

  writeFileSync(OUTPUT_PATH, indexContent);

  // ── Generate components.ts (Lazy Imports) ──
  let componentsContent = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from "react"

export const Components: Record<string, React.LazyExoticComponent<any>> = {
`;

  Index.forEach((item: any) => {
    const componentPath = item.files[0].replace(/\.tsx?$/, '');
    componentsContent += `  "${item.name}": React.lazy(() => import("@/registry/${componentPath}")),\n`;
  });

  componentsContent += `};`;

  writeFileSync(COMPONENTS_PATH, componentsContent);

  console.log('✅ Slash UI Registry updated');
}

buildRegistry();