// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from "react"

export const Components: Record<string, React.LazyExoticComponent<any>> = {
  "neubrutal-button": React.lazy(() => import("@/registry/ui/buttons/neubrutal-button")),
  "dot-cursor": React.lazy(() => import("@/registry/ui/cursors/dot-cursor")),
  "floating-navbar": React.lazy(() => import("@/registry/ui/navbars/floating-navbar")),
  "VisualScrollbar": React.lazy(() => import("@/registry/ui/scrollbars/minimal-scrollbar")),
  "strike-reveal": React.lazy(() => import("@/registry/ui/hover-effects/strike-reveal")),
  "infinity-slider": React.lazy(() => import("@/registry/ui/3d-sliders/infinity-slider")),
  "stroke-cards": React.lazy(() => import("@/registry/ui/cards/stroke-cards")),
  "arc-slider": React.lazy(() => import("@/registry/ui/3d-sliders/arc-slider")),
  "animated-header": React.lazy(() => import("@/registry/ui/scroll-effects/animated-header")),
};