// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "neubrutal-button": {
      name: "neubrutal-button",
      type: "ui",
      // FIX: Ensure the import points to the correct relative path
      component: React.lazy(() => import("../registry/ui/neubrutal-button")),
      files: ["ui/neubrutal-button.tsx"],
      category: "buttons",
      content: ``,
      description: `
### Neubrutal 3D Button
A modern 3D button component with a soft neumorphic depth and smooth press animation. Designed to feel tactile and interactive, it visually responds to user interaction with layered shadows and subtle motion.

**Interaction Type**
* Click to press with realistic depth animation
* Smooth transition between idle and active states
* Optional hover and focus effects

---

### How to use
\`\`\`tsx
import { NeubrutalButton } from "@/components/ui/neubrutal-button";

const Example = () => {
  return (
    <NeubrutalButton onClick={() => alert("Clicked!")}>
      Click Me!
    </NeubrutalButton>
  );
};
\`\`\`

---

### Props
| Prop | Description |
| :--- | :--- |
| **children** | Button label or content |
| **onClick** | Click handler function |
| **className** | Additional Tailwind classes |

---

**License & Usage**
Free to use and modify in both personal and commercial projects.
`,
      install: "npm install framer-motion lucide-react",
    },
  }
};