// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Slim metadata only — safe to import from layout/search UI on every page.
// Do NOT add component/content/description fields here; use __registry__/index.ts for that.

export const SearchIndex = [
  {
    "name": "neubrutal-button",
    "category": "buttons",
    "path": "/component/neubrutal-button"
  },
  {
    "name": "dot-cursor",
    "category": "cursors",
    "path": "/component/dot-cursor"
  },
  {
    "name": "floating-navbar",
    "category": "navbars",
    "path": "/component/floating-navbar"
  },
  {
    "name": "VisualScrollbar",
    "category": "scrollbars",
    "path": "/component/VisualScrollbar"
  },
  {
    "name": "strike-reveal",
    "category": "hover-effects",
    "path": "/component/strike-reveal"
  },
  {
    "name": "infinity-slider",
    "category": "3d-sliders",
    "path": "/component/infinity-slider"
  },
  {
    "name": "stroke-cards",
    "category": "cards",
    "path": "/component/stroke-cards"
  },
  {
    "name": "arc-slider",
    "category": "3d-sliders",
    "path": "/component/arc-slider"
  },
  {
    "name": "animated-header",
    "category": "scroll-effects",
    "path": "/component/animated-header"
  }
] as const;
